name: EKS - Preview/Check STAGING 🔍
on:
  pull_request:
    branches:
      - develop
    paths:
      - 'aws/eks-gitops/**'
  push:
    branches:
      - develop
    paths:
      -  'aws/eks-gitops/**'
  workflow_dispatch:
  schedule:
    - cron: '0 8-17 * * *'
  #  Cron above will run on main only https://stackoverflow.com/questions/58798886/github-actions-schedule-operation-on-branch

jobs:
  call-preview-workflow:
    uses: ./.github/workflows/aws_eks_preview.yml
    with:
      pulumi-stack: staging
    secrets: inherit