name: EKS - Preview/Check STAGING 🔍
on:
  pull_request:
    branches:
      - main
    paths:
      - 'aws/eks-gitops/**'
  push:
    branches:
      - main
    paths:
      -  'aws/eks-gitops/**'
  workflow_dispatch:
  # schedule:
  #   branches:
  #     - main
  #   - cron: '0 8-17 * * *'

jobs:
  call-preview-workflow:
    uses: ./.github/workflows/aws_eks_preview.yml
    with:
      pulumi-stack: prod
    secrets: inherit